#!/usr/bin/env python3
"""Embed the pinned, unmodified fonts so launching needs no asset search path."""
import argparse
import hashlib
import json
from pathlib import Path

p = argparse.ArgumentParser()
p.add_argument('--assets', type=Path, required=True)
p.add_argument('--manifest', type=Path, required=True)
p.add_argument('--output', type=Path, required=True)
a = p.parse_args()
pins = json.loads(a.manifest.read_text())['fonts']['files']
lines = ['// Generated by embed_fonts.py.', '#pragma once', 'namespace breakout::fonts {']
for filename, symbol in [('LiberationSans-Regular.ttf', 'Body'),
                         ('LiberationSans-Bold.ttf', 'Bold'),
                         ('LiberationMono-Regular.ttf', 'Mono')]:
    data = (a.assets / filename).read_bytes()
    if hashlib.sha256(data).hexdigest() != pins[filename]:
        raise SystemExit('Font checksum mismatch: ' + filename)
    lines.append('inline constexpr unsigned char ' + symbol + '[] = {')
    for start in range(0, len(data), 32):
        lines.append(','.join(str(b) for b in data[start:start + 32]) + ',')
    lines.append('};')
lines.append('}')
a.output.parent.mkdir(parents=True, exist_ok=True)
a.output.write_text('\n'.join(lines) + '\n')
