#!/usr/bin/env python3
"""Generate compiled lessons and independent, entirely offline guides.

Only Python's standard library is required. Layout substitutions come from the
same machine-readable layout used to generate NASM offsets; unresolved tokens
are an error so rebuilt guides cannot silently teach stale offsets.
"""
import argparse
import html
import json
import re
from pathlib import Path

TOKEN = re.compile(r"\{\{([A-Za-z0-9_.]+)\}\}")


def flatten(value, prefix=""):
    result = {}
    if isinstance(value, dict):
        for key, child in value.items():
            result.update(flatten(child, f"{prefix}.{key}" if prefix else key))
    elif isinstance(value, (str, int, float)):
        result[prefix] = str(value)
    return result


def expand(value, variables):
    if isinstance(value, str):
        def replace(match):
            key = match.group(1)
            if key not in variables:
                raise ValueError(f"No layout value supplied for {key}")
            return variables[key]
        return TOKEN.sub(replace, value)
    if isinstance(value, list):
        return [expand(child, variables) for child in value]
    if isinstance(value, dict):
        return {key: expand(child, variables) for key, child in value.items()}
    return value


def cpp_string(value):
    # Encode UTF-8 explicitly; fixed-width octal avoids \x consuming following
    # hex digits. Escape every control byte, quotes and backslashes.
    parts = []
    for byte in value.encode("utf-8"):
        if byte == 34:
            parts.append('\\"')
        elif byte == 92:
            parts.append('\\\\')
        elif 32 <= byte <= 126:
            parts.append(chr(byte))
        else:
            parts.append(f"\\{byte:03o}")
    return 'std::string("' + ''.join(parts) + '", ' + str(len(value.encode("utf-8"))) + ')'


CHECK = re.compile(r"^(fired|hit|patched|restored|primary|complete|moved|moved_right|moved_left|"
                   r"zone:[a-z]+|action:[a-z_]+|write:[a-z_]+|relay:[0-9]+)$")


def validate(data):
    lessons = data["lessons"]
    if [lesson["id"] for lesson in lessons] != list(range(0, 14)):
        raise ValueError("Lessons must contain rooms 0 through 13 in order")
    if not data.get("find_rookie", "").strip():
        raise ValueError("find_rookie recipe is missing")
    for lesson in lessons:
        for key in ("title", "chapter", "goal", "learned"):
            if not isinstance(lesson.get(key), str) or not lesson[key].strip():
                raise ValueError(f"Room {lesson['id']} lacks {key}")
        explain = lesson.get("explain")
        if not isinstance(explain, list) or not explain or any(
                not isinstance(x.get("title"), str) or not x["title"].strip() or
                not isinstance(x.get("text"), str) or not x["text"].strip() for x in explain):
            raise ValueError(f"Room {lesson['id']} needs explain sections with a title and text")
        if not lesson.get("steps"):
            raise ValueError(f"Room {lesson['id']} has no steps")
        for step in lesson["steps"]:
            if step.get("where") not in ("game", "reclass") or not step.get("text", "").strip():
                raise ValueError(f"Room {lesson['id']} has an incomplete step")
            if "check" in step and not CHECK.match(step["check"]):
                raise ValueError(f"Room {lesson['id']} has an unknown check {step['check']}")
            loop = step.get("loop", 0)
            if not isinstance(loop, int) or loop < 0 or loop > len(lesson["steps"]):
                raise ValueError(f"Room {lesson['id']} has an invalid loop target")
            for key in ("why", "see"):
                if key in step and (not isinstance(step[key], str) or not step[key].strip()):
                    raise ValueError(f"Room {lesson['id']} has an empty {key}")
            if step["text"].count("`") % 2:
                raise ValueError(f"Room {lesson['id']} has an unbalanced label backtick")
    return lessons


def generate_cpp(data, lessons):
    lines = ['// Generated by tools/generate-lessons.py; edit content/lessons.json.',
             '#include "tutorial.h"', 'namespace breakout {',
             'const std::vector<Lesson>& Lessons() {',
             '    static const std::vector<Lesson> lessons = {']
    for lesson in lessons:
        lines.append('        {' + str(lesson['id']) + ', ' + ', '.join(
            cpp_string(lesson[key]) for key in ('title', 'chapter', 'goal')) + ',')
        lines.append('            {')
        for step in lesson['steps']:
            lines.append('                {' + ', '.join(cpp_string(step.get(key, '')) for key in
                                                       ('where', 'text', 'check')) + ', ' + str(step.get('loop', 0)) + ', ' +
                         cpp_string(step.get('why', '')) + ', ' + cpp_string(step.get('see', '')) + '},')
        lines.append('            },')
        lines.append('            ' + cpp_string(lesson['learned']) + ', ' + cpp_string(lesson.get('restore', '')) + ',')
        lines.append('            {' + ', '.join('{' + cpp_string(x['title']) + ', ' + cpp_string(x['text']) + '}' for x in lesson['explain']) + '}},')
    lines += ['    };', '    return lessons;', '}',
              'const std::string& FindRookieRecipe() {',
              '    static const std::string recipe = ' + cpp_string(data['find_rookie']) + ';',
              '    return recipe;', '}', '}', '']
    return '\n'.join(lines)


TAG = {'game': 'IN GAME', 'reclass': 'IN RECLASS'}


def markdown_text(value):
    value = re.sub(r"(?m)^pushfq\n.*?^popfq$", lambda m: "```nasm\n" + m.group(0) + "\n```",
                   value, flags=re.DOTALL)
    return value


def generate_markdown(data, lessons):
    lines = ['# ReClass: Breakout — Offline guide', '', data['introduction'], '',
             'This guide has no network dependencies. Keep it open beside ReClass: a ReClass debugger pause also freezes the game window.', '']
    chapter = None
    for lesson in lessons:
        if lesson['chapter'] != chapter:
            chapter = lesson['chapter']
            lines += [f"# {chapter}", '']
        lines += [f"## Room {lesson['id']}: {lesson['title']}", '', '**Goal:** ' + lesson['goal'], '']
        for index, step in enumerate(lesson['steps'], 1):
            lines += [f"{index}. **{TAG[step['where']]}** — " + markdown_text(step['text']), '']
            if step.get('why'):
                lines += [f"   *Why:* {step['why']}", '']
            if step.get('see'):
                lines += [f"   *You should see:* {step['see']}", '']
            if step.get('loop'):
                lines += [f"   *Still too many results? Repeat steps {step['loop']}–{index}. Several rounds are normal.*", '']
        if lesson.get('restore'):
            lines += ['**Before leaving:** ' + lesson['restore'], '']
        lines += ['*What you learned:* ' + lesson['learned'], '']
        lines += [f"### Room {lesson['id']} explained", '']
        for section in lesson['explain']:
            lines += [f"#### {section['title']}", '', section['text'], '']
    lines += ['## Find ROOKIE again', '', data['find_rookie'], '']
    return '\n'.join(lines)


def html_text(value):
    escaped = html.escape(value)
    return re.sub(r"`([^`]+)`", r'<code>\1</code>', escaped)


def generate_html(data, lessons):
    # Plain text with retained line breaks; no remote resources or JavaScript.
    lines = ['<!doctype html><html lang="en"><head><meta charset="utf-8">',
             '<meta name="viewport" content="width=device-width, initial-scale=1">',
             '<title>ReClass: Breakout — Offline guide</title>',
             '<style>body{margin:auto;padding:2rem;max-width:60rem;background:#101923;color:#eef3f7;font:18px/1.6 system-ui,sans-serif}a{color:#8ed5ff}nav a{display:inline-block;margin:0 .8rem .4rem 0}h1,h2{line-height:1.25}h2{margin-top:2.5rem;border-top:1px solid #526272;padding-top:1rem}ol li{margin:.6rem 0;white-space:pre-wrap}.tag{display:inline-block;font-size:.72rem;font-weight:700;padding:.05rem .45rem;border-radius:.6rem;margin-right:.5rem}.game{background:#173d36;color:#48dbb5}.reclass{background:#2c2047;color:#b084ff}code{background:#1e2c3d;color:#48dbb5;padding:.05rem .3rem;border-radius:.25rem}.goal{border-left:3px solid #48dbb5;padding-left:1rem}.learned{color:#a9bbd0;font-style:italic}.restore{color:#f9bf57}.repeat{color:#f9bf57}.why{color:#a9bbd0}.explain{border:1px solid #526272;border-radius:.4rem;padding:.4rem 1rem;margin:1rem 0}.explain summary{cursor:pointer;color:#48dbb5;font-weight:700}.callout{border-left:3px solid #f9bf57;padding-left:1rem;color:#f9bf57}pre{background:#0c131d;color:#48dbb5;padding:.6rem;border-radius:.3rem;overflow-x:auto}.see{color:#f9bf57}@media print{body{background:white;color:black}}</style>',
             '</head><body><h1>ReClass: Breakout — Offline guide</h1>',
             '<p>' + html_text(data['introduction']) + '</p>',
             '<p>Keep this guide open beside ReClass: a ReClass debugger pause also freezes the game window.</p>', '<nav aria-label="Rooms">']
    for lesson in lessons:
        lines.append(f'<a href="#room-{lesson["id"]}">{lesson["id"]}. {html.escape(lesson["title"])}</a>')
    lines += ['<a href="#find-rookie">Find ROOKIE again</a>', '</nav>']
    for lesson in lessons:
        lines += [f'<article id="room-{lesson["id"]}"><h2>Room {lesson["id"]}: {html.escape(lesson["title"])} <small>— {html.escape(lesson["chapter"])}</small></h2>',
                  '<p class="goal">' + html_text(lesson['goal']) + '</p>', '<ol>']
        for step in lesson['steps']:
            repeat = f'<br><em class="repeat">Still too many results? Repeat steps {step["loop"]}–{lesson["steps"].index(step) + 1}. Several rounds are normal.</em>' if step.get('loop') else ''
            why = f'<br><span class="why">Why: {html_text(step["why"])}</span>' if step.get('why') else ''
            see = f'<br><span class="see">You should see: {html_text(step["see"])}</span>' if step.get('see') else ''
            lines.append(f'<li><span class="tag {step["where"]}">{TAG[step["where"]]}</span>' + html_text(step['text']) + why + see + repeat + '</li>')
        lines.append('</ol>')
        if lesson.get('restore'):
            lines.append('<p class="restore">Before leaving: ' + html_text(lesson['restore']) + '</p>')
        lines += ['<p class="learned">What you learned: ' + html_text(lesson['learned']) + '</p>']
        lines.append('<details class="explain"><summary>Explained</summary>')
        for section in lesson['explain']:
            lines.append('<h3>' + html.escape(section['title']) + '</h3>')
            for block in section['text'].split('\n\n'):
                if block.startswith('```'):
                    lines.append('<pre>' + html.escape(block.strip('`').strip('\n')) + '</pre>')
                elif block.startswith('- '):
                    lines.append('<ul>' + ''.join('<li>' + html_text(item[2:]) + '</li>' for item in block.split('\n')) + '</ul>')
                elif block.startswith('> '):
                    lines.append('<p class="callout">' + html_text(block[2:]) + '</p>')
                else:
                    lines.append('<p>' + html_text(block) + '</p>')
        lines += ['</details>', '</article>']
    lines += ['<article id="find-rookie"><h2>Find ROOKIE again</h2><p>' + html_text(data['find_rookie']) + '</p></article>', '</body></html>\n']
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--input', type=Path, required=True)
    parser.add_argument('--output-dir', type=Path, required=True)
    parser.add_argument('--layout', type=Path)
    args = parser.parse_args()
    data = json.loads(args.input.read_text(encoding='utf-8'))
    variables = flatten(data.get('layout_defaults', {}))
    if args.layout:
        layout = json.loads(args.layout.read_text(encoding='utf-8'))
        variables.update(flatten(layout))
        for structure in layout.get('structs', []):
            name = structure['name'].lower()
            variables[name + '.size'] = str(structure['size'])
            for field in structure['fields']:
                variables[name + '.' + field['name']] = str(field['offset'])
                variables[name + '.' + field['name'] + '.size'] = str(field['size'])
        if 'actor.ammo' in variables and 'actor.faction' in variables:
            variables['actor.faction_from_ammo'] = str(int(variables['actor.faction']) - int(variables['actor.ammo']))
    data = expand(data, variables)
    lessons = validate(data)
    args.output_dir.mkdir(parents=True, exist_ok=True)
    outputs = {'lessons.generated.cpp': generate_cpp(data, lessons),
               'GUIDE.md': generate_markdown(data, lessons),
               'GUIDE.html': generate_html(data, lessons)}
    for name, value in outputs.items():
        (args.output_dir / name).write_text(value, encoding='utf-8', newline='\n')


if __name__ == '__main__':
    main()
