#!/usr/bin/env python3
"""Generate compiled lessons and independent, entirely offline guides.

Only Python's standard library is required. Layout substitutions come from the
same machine-readable layout used to generate NASM offsets; unresolved tokens
are an error so rebuilt guides cannot silently teach stale offsets.
"""
import argparse
import html
import json
import re
from pathlib import Path

TOKEN = re.compile(r"\{\{([A-Za-z0-9_.]+)\}\}")


def flatten(value, prefix=""):
    result = {}
    if isinstance(value, dict):
        for key, child in value.items():
            result.update(flatten(child, f"{prefix}.{key}" if prefix else key))
    elif isinstance(value, (str, int, float)):
        result[prefix] = str(value)
    return result


def expand(value, variables):
    if isinstance(value, str):
        def replace(match):
            key = match.group(1)
            if key not in variables:
                raise ValueError(f"No layout value supplied for {key}")
            return variables[key]
        return TOKEN.sub(replace, value)
    if isinstance(value, list):
        return [expand(child, variables) for child in value]
    if isinstance(value, dict):
        return {key: expand(child, variables) for key, child in value.items()}
    return value


def cpp_string(value):
    # Encode UTF-8 explicitly; fixed-width octal avoids \x consuming following
    # hex digits. Escape every control byte, quotes and backslashes.
    parts = []
    for byte in value.encode("utf-8"):
        if byte == 34:
            parts.append('\\"')
        elif byte == 92:
            parts.append('\\\\')
        elif 32 <= byte <= 126:
            parts.append(chr(byte))
        else:
            parts.append(f"\\{byte:03o}")
    return 'std::string("' + ''.join(parts) + '", ' + str(len(value.encode("utf-8"))) + ')'


def validate(data):
    lessons = data["lessons"]
    if [lesson["id"] for lesson in lessons] != list(range(1, 13)):
        raise ValueError("Lessons must contain rooms 1 through 12 in order")
    for lesson in lessons:
        for key in ("title", "objective", "concept", "restoration"):
            if not isinstance(lesson[key], str) or not lesson[key].strip():
                raise ValueError(f"Room {lesson['id']} lacks {key}")
        for key in ("steps", "hints", "solutions"):
            if not isinstance(lesson[key], list) or not lesson[key]:
                raise ValueError(f"Room {lesson['id']} lacks {key}")
        for step in lesson["steps"]:
            if any(not isinstance(step.get(key), str) or not step[key].strip()
                   for key in ("title", "text", "expected")):
                raise ValueError(f"Room {lesson['id']} has an incomplete step")
        for key in ("hints", "solutions"):
            if any(not isinstance(item, str) or not item.strip() for item in lesson[key]):
                raise ValueError(f"Room {lesson['id']} has an incomplete {key}")
    return lessons


def generate_cpp(lessons):
    lines = ['// Generated by tools/generate-lessons.py; edit content/lessons.json.',
             '#include "tutorial.h"', 'namespace breakout {',
             'const std::vector<Lesson>& Lessons() {',
             '    static const std::vector<Lesson> lessons = {']
    for lesson in lessons:
        lines.append('        {' + str(lesson['id']) + ', ' + ', '.join(
            cpp_string(lesson[key]) for key in ('title', 'objective', 'concept')) + ',')
        lines.append('            {')
        for step in lesson['steps']:
            lines.append('                {' + ', '.join(cpp_string(step[key]) for key in
                                                       ('title', 'text', 'expected')) + '},')
        lines.append('            },')
        for key in ('hints', 'solutions'):
            lines.append('            {' + ', '.join(cpp_string(item) for item in lesson[key]) + '},')
        lines.append('            ' + cpp_string(lesson['restoration']) + '},')
    lines += ['    };', '    return lessons;', '}', '}', '']
    return '\n'.join(lines)


def markdown_text(value):
    # Fence contiguous worked NASM bodies so Markdown viewers preserve their
    # line structure as faithfully as the plain text and HTML presentations.
    return re.sub(r"(?m)(?:^dec dword \[rax\]\n)?^pushfq\n.*?^popfq$",
                  lambda match: "```nasm\n" + match.group(0) + "\n```",
                  value, flags=re.DOTALL)


def generate_markdown(data, lessons):
    lines = ['# ReClass: Breakout — Offline guide', '', data['introduction'], '',
             'This guide has no network dependencies. Keep it open beside ReClass.', '']
    for lesson in lessons:
        lines += [f"## {lesson['id']}. {lesson['title']}", '', lesson['objective'], '', lesson['concept'], '']
        for index, step in enumerate(lesson['steps'], 1):
            lines += [f"### Step {index}: {step['title']}", '', markdown_text(step['text']), '',
                      'Expected observation: ' + step['expected'], '']
        lines += ['### Hints', '']
        for item in lesson['hints']:
            lines += [markdown_text(item), '']
        lines += ['### Full solution', '']
        for item in lesson['solutions']:
            lines += [markdown_text(item), '']
        lines += ['### Restoration', '', lesson['restoration'], '']
    return '\n'.join(lines)


def generate_html(data, lessons):
    # Content is rendered as plain text with retained line breaks, including
    # literal NASM. No HTML interpolation, remote resources or JavaScript.
    esc = html.escape
    paragraphs = lambda value: '<div class="text">' + esc(value) + '</div>'
    lines = ['<!doctype html><html lang="en"><head><meta charset="utf-8">',
             '<meta name="viewport" content="width=device-width, initial-scale=1">',
             '<title>ReClass: Breakout — Offline guide</title>',
             '<style>body{margin:auto;padding:2rem;max-width:76rem;background:#101923;color:#eef3f7;font:18px/1.6 system-ui,sans-serif}a{color:#8ed5ff}nav a{display:inline-block;margin:0 .8rem .4rem 0}.text{white-space:pre-wrap;overflow-wrap:anywhere;margin:1rem 0}h1,h2,h3{line-height:1.25}h2{margin-top:3rem;border-top:1px solid #526272;padding-top:1rem}.expected{border-left:3px solid #8ed5ff;padding-left:1rem}details{border:1px solid #526272;padding:.8rem;margin:1rem 0}summary{cursor:pointer}article{scroll-margin-top:1rem}@media print{body{background:white;color:black}details{display:block}a{color:black}}</style>',
             '</head><body><h1>ReClass: Breakout — Offline guide</h1>',
             paragraphs(data['introduction']),
             '<p>This guide has no network dependencies. Keep it open beside ReClass. Browser zoom changes text size.</p>', '<nav aria-label="Rooms">']
    for lesson in lessons:
        lines.append(f'<a href="#room-{lesson["id"]}">{lesson["id"]}. {esc(lesson["title"])}</a>')
    lines.append('</nav>')
    for lesson in lessons:
        lines += [f'<article id="room-{lesson["id"]}"><h2>{lesson["id"]}. {esc(lesson["title"])}</h2>',
                  paragraphs(lesson['objective']), paragraphs(lesson['concept'])]
        for index, step in enumerate(lesson['steps'], 1):
            lines += [f'<h3>Step {index}: {esc(step["title"])}</h3>', paragraphs(step['text']),
                      '<div class="expected">' + paragraphs('Expected observation: ' + step['expected']) + '</div>']
        for key, title in [('hints', 'Hints'), ('solutions', 'Full solution')]:
            lines.append('<details><summary>' + title + '</summary>')
            for item in lesson[key]:
                lines.append(paragraphs(item))
            lines.append('</details>')
        lines += ['<h3>Restoration</h3>', paragraphs(lesson['restoration']), '</article>']
    lines.append('</body></html>\n')
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--input', type=Path, required=True)
    parser.add_argument('--output-dir', type=Path, required=True)
    parser.add_argument('--layout', type=Path)
    args = parser.parse_args()
    data = json.loads(args.input.read_text(encoding='utf-8'))
    variables = flatten(data.get('layout_defaults', {}))
    if args.layout:
        layout = json.loads(args.layout.read_text(encoding='utf-8'))
        variables.update(flatten(layout))
        for structure in layout.get('structs', []):
            name = structure['name'].lower()
            variables[name + '.size'] = str(structure['size'])
            for field in structure['fields']:
                variables[name + '.' + field['name']] = str(field['offset'])
                variables[name + '.' + field['name'] + '.size'] = str(field['size'])
        if 'actor.ammo' in variables and 'actor.faction' in variables:
            variables['actor.faction_from_ammo'] = str(int(variables['actor.faction']) - int(variables['actor.ammo']))
    data = expand(data, variables)
    lessons = validate(data)
    # General operating instructions appear identically in every game's lesson
    # and in its offline counterpart, so Copy instructions retains them.
    for lesson in lessons:
        lesson['concept'] += '\n\n' + data['common_instructions']
    args.output_dir.mkdir(parents=True, exist_ok=True)
    outputs = {'lessons.generated.cpp': generate_cpp(lessons),
               'GUIDE.md': generate_markdown(data, lessons),
               'GUIDE.html': generate_html(data, lessons)}
    for name, value in outputs.items():
        (args.output_dir / name).write_text(value, encoding='utf-8', newline='\n')


if __name__ == '__main__':
    main()
