#!/usr/bin/env python3
"""One layout schema supplies C++ types, NASM offsets and learner documentation."""
import argparse
import json
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent
p = argparse.ArgumentParser()
p.add_argument('--schema', type=Path, default=BASE / 'tools/layout.json')
p.add_argument('--output-dir', type=Path, default=BASE / 'build/generated')
p.add_argument('--guide', type=Path, default=None)
a = p.parse_args()
if a.guide is None:
    a.guide = a.output_dir / 'layout.md'
schema = json.loads(a.schema.read_text())
scalar = {'int32': 'std::int32_t', 'uint32': 'std::uint32_t', 'uint8': 'std::uint8_t', 'float32': 'float', 'char': 'char'}
def declaration(field):
    typ = field['type']
    if '[' in typ:
        base, count = typ.split('[')
        return f"{scalar.get(base, base)} {field['name']}[{count};"
    return f"{scalar.get(typ, typ)} {field['name']};"
header = ['// Generated by tools/generate_layout.py; edit tools/layout.json.', '#pragma once', '#include <cstddef>', '#include <cstdint>', '#include <type_traits>', 'namespace breakout {']
asm = ['; Generated by tools/generate_layout.py; edit tools/layout.json.']
guide = ['# Native teaching layout (x64)', '', 'The module symbol `breakout_world_root` points to World. Pointer fields are 8 bytes. Player faction is 1; enemy faction is 2. Power is flags bit 0, alarm is bit 1. Engineer clearance is 2.', '']
for struct in schema['structs']:
    name = struct['name']
    header.append(f'struct {name};')
for struct in schema['structs']:
    name = struct['name']
    header.append(f'struct alignas({struct["alignment"]}) {name} {{')
    header.extend('    ' + declaration(f) for f in struct['fields'])
    header.extend(['};', f'static_assert(std::is_standard_layout<{name}>::value, "{name} must be standard layout");', f'static_assert(sizeof({name}) == {struct["size"]}, "{name} size");', f'static_assert(alignof({name}) == {struct["alignment"]}, "{name} alignment");'])
    asm.append(f'%define {name.upper()}_SIZE {struct["size"]}')
    guide.extend([f'## {name} ({struct["size"]} bytes)', '', '| Field | Type | Offset | Bytes |', '|---|---|---:|---:|'])
    for f in struct['fields']:
        header.append(f'static_assert(offsetof({name}, {f["name"]}) == {f["offset"]}, "{name}.{f["name"]} offset");')
        asm.append(f'%define {name.upper()}_{f["name"].upper()} {f["offset"]}')
        guide.append(f'| {f["name"]} | `{f["type"]}` | {f["offset"]} | {f["size"]} |')
    guide.append('')
header.extend(['static_assert(sizeof(void*) == 8, "Breakout requires x64");', 'constexpr std::uint32_t PlayerFaction = 1, EnemyFaction = 2;', 'constexpr std::uint32_t PowerFlag = 1, AlarmFlag = 2, EngineerClearance = 2;', '} // namespace breakout', ''])
asm.extend(['%define PLAYER_FACTION 1', '%define ENEMY_FACTION 2', '%define ENGINEER_CLEARANCE 2', '%define POWER_FLAG 1', '%define ALARM_FLAG 2', ''])
a.output_dir.mkdir(parents=True, exist_ok=True)
a.guide.parent.mkdir(parents=True, exist_ok=True)
(a.output_dir / 'layout.h').write_text('\n'.join(header))
(a.output_dir / 'layout.inc').write_text('\n'.join(asm))
a.guide.write_text('\n'.join(guide))
